version: "3.9"

services:
  web:
    build: .
    container_name: skew_batch
    ports:
      - "5000:5000"   # Flask
      - "8050:8050"   # Dash
    volumes:
      - .:/app        # For development hot reload
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
    restart: always
