version: "3.9"

services:
  web:
    build: .
    container_name: skew_batch
    ports:
      - "5000:5000"
      - "8050:8050"     # Dash port exposed to host
    volumes:
      - .:/app          # Live reload for development
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
    restart: always
